services:
  api:
    image: hibiki31/hinav-api:latest
    restart: always
    hostname: hinav-api
    volumes:
      # キャッシュの作成場所
      - "${CACHE_DIR}:/opt/data/book_cache/"
      # サムネイルの作成先
      - "${THUM_DIR}:/opt/data/book_thum/"
      # ライブラリ
      - "${LIBRARY_DIR}:/opt/data/book_library/"
      # ZIPのインポート監視フォルダ
      - "${SEND_DIR}:/opt/data/book_send/"
      # ZIPのエクスポート先
      - "${EXPORT_DIR}:/opt/data/book_export/"
      # 失敗したZIP
      - "${FAIL_DIR}:/opt/data/book_fail/"
      # データベースやログファイル
      - "${APP_DIR}:/opt/data/app_data/"
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@hinav-db:5432/${POSTGRES_DB}"
      SECRET_KEY: "${SECRET_KEY}"
  web:
    image: hibiki31/hinav-web:latest
    restart: always
    ports:
      - 8080:80
    hostname: hinav-web
  db:
    image: postgres:13.5
    restart: unless-stopped
    hostname: hinav-db
    volumes:
      - hinav-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
volumes:
  hinav-db: